### ISSUE TITLE
The cluster load imbalance should include the duration requirement

### ISSUE THREAD

**Issue by binder1234** [NetAppDocs/active-iq-unified-manager#10]
Page: [Types of system-defined performance threshold policies](https://docs.netapp.com/us-en/active-iq-unified-manager/performance-checker/reference_types_of_system_defined_performance_threshold_policies.html)

It does this by comparing the performance capacity used value for all nodes in the cluster to see if there is a load difference of 30% between any nodes. This is a warning event.

This statement should indicate that it has to exceed the 30% threshold for more than 24 hours.

**Comment by netapp-manini** [comment]
Thanks for writing in, I am looking into it.

**Comment by binder1234** [comment]
Any updates?

**Comment by netapp-manini** [comment]
Hi, the reported issue will be fixed in the 9.11 and 9.10 docs retroactively as these documents have already been released. We are planning on a refresh and that will be available by this month. I will update this issue.

**Comment by binder1234** [comment]
Thanks.
