### ISSUE TITLE
Remove references to WFA as a requirement for AIQUM

### ISSUE THREAD

**Issue by crankbird** [NetAppDocs/active-iq-unified-manager#11]
Page: [Setting up protection relationships in Unified Manager](https://docs.netapp.com/us-en/active-iq-unified-manager/data-protection/task_set_up_protection_relationships_in_unified_manager.html)

WFA is now EOA, we shouldnt be referring to it as being required any more, I thought we'd replaced all this with Ansible.

**Comment by netapp-manini** [comment]
Thanks for writing in. We are analyzing this issue.

**Comment by netapp-manini** [comment]
Hi, I discussed this issue with product management and looks like we need to maintain this for some more time. Here is the response:

"WFA 5.1.x is supported till Feb 2025 and 9.12 would qualify WFA so, for now, we can keep WFA in documentation. 

We would take decision on future versions post 9.12 and will update you on the same. "

Unless there are further queries, I shall close this issue in a couple of days. Please advise.
