### ISSUE TITLE
Option for events to be listed as a CSV

### ISSUE THREAD

**Issue by shawnmkim** [NetAppDocs/active-iq-unified-manager#19]
Page: [Aggregate events](https://docs.netapp.com/us-en/active-iq-unified-manager/events/reference_aggregate_events.html)

I am trying to get a complete list of events and was wondering if there is a complete table with all the events in a CSV or similar documents, so that all events can be on a single list that we can go over altogether.

**Comment by netapp-manini** [comment]
Hi [shawnmkim](https://github.com/shawnmkim),
Thanks for writing in. We are looking into this issue, and will update you on the same.

**Comment by netapp-manini** [comment]
You can download the PDF for these topics from https://docs.netapp.com/us-en/active-iq-unified-manager/pdfs/sidebar/List_of_events_and_severity_types.pdf

You can generate the PDF for this set of topics from this link: [Aggregate events](https://docs.netapp.com/us-en/active-iq-unified-manager/events/reference_aggregate_events.html)

![image](https://user-images.githubusercontent.com/59729581/201842619-38bba39b-9c94-415c-9d84-e43eabaf3b90.png)

**Comment by netapp-manini** [comment]
Do let us know of any further concern. If not, will close this issue. Thank you!

**Comment by netapp-manini** [comment]
We do not have an automated way to deliver a .csv format of UM events. l will follow-up internally and get back on his request for a .csv format of all the events. I shall update this post when an update is available.

**Comment by netapp-manini** [comment]
We have not been able to come up with a solution. Closing this issue for now. We will reopen this issue when a resolution is available.
