### ISSUE TITLE
Clarification on HTTPS certificate generation

### ISSUE THREAD

**Issue by pvkoppen** [NetAppDocs/active-iq-unified-manager#20]
Page: [HTTPS Certificate page](https://docs.netapp.com/us-en/active-iq-unified-manager/config/reference_https_dialog_box_ocf.html)

Can you please update the page and the help section with information that the button "Regenerate HTTPS Certificate" generates a self-signed certificate?

**Comment by netapp-manini** [comment]
Thanks for writing in. We are investigating the issue, and will update it with the resolution soon.

**Comment by netapp-shwetav** [comment]
We are tracking this issue here- [Burt 1515107](http://burtview.netapp.com/burt/burt-bin/start?burt-id=1515107)
We are keeping this issue open because we have not received any further information.
