### ISSUE TITLE
Feature change - update certificate details

### ISSUE THREAD

**Issue by pvkoppen** [NetAppDocs/active-iq-unified-manager#21]
Page: [HTTPS Certificate page](https://docs.netapp.com/us-en/active-iq-unified-manager/config/reference_https_dialog_box_ocf.html)

Can the AIQUM please get the feature to update the certificate details?
The details on the current certificate are close but we would like to add an alias to the certificate (ocum.[domain].com and aiqum.[domain].com)

**Comment by netapp-manini** [comment]
Thanks for writing in. We are looking into this issue, and will update this thread with the resolution soon.

**Comment by netapp-manini** [comment]
@pvkoppen is this a request for additional feature/information in the certificate in Unified Manager? Kindly clarify if this is a doc enhancement, and if so, what is the exact information that is lacking on this page?

[HTTPS Certificate page](https://docs.netapp.com/us-en/active-iq-unified-manager/config/reference_https_dialog_box_ocf.html)

**Comment by pvkoppen** [comment]
> @pvkoppen It will be a great help if you provide more details. Is it related to feature updates? Please let me know the exact changes. cc: @netapp-manini

Hi, yes this is a feature request doe AIQUM (and for the NetApp ONTAP Software if you have contact to there)
The request to generate a certificate request works, but i would love to have teh ability to be able to add an alias.
Teh default uses the [servername].[domainname] and i would love to be able to add [alias].[domainname] at teh request time

Peter

**Comment by netapp-shwetav** [comment]
Hi @pvkoppen 
cc: @netapp-manini 
This is documented under https://docs.netapp.com/us-en/active-iq-unified-manager/config/task_generate_an_https_security_certificate_ocf.html. Please check point 3. When AIQUM is installed, it has a default certificate. But by choosing Regenerate HTTPS Certificate>>Update the Current Certificate Attributes>>Alternative Names, you can add the alias. Does this address your question?  If not, please provide more information about the feature request along with some examples.

**Comment by netapp-manini** [comment]
Hi @pvkoppen 
cc @netapp-shwetav 
Can you please let us know whether the link sent earlier [https://docs.netapp.com/us-en/active-iq-unified-manager/config](https://docs.netapp.com/us-en/active-iq-unified-manager/config/task_generate_an_https_security_certificate_ocf.html) is what clarifies your doubt?

**Comment by netapp-shwetav** [comment]
We are tracking this issue here- [Burt 1515107](http://burtview.netapp.com/burt/burt-bin/start?burt-id=1515107)
We are keeping this issue open because we have not received any further information.

**Comment by netapp-manini** [comment]
Because we have not heard back from the filer, we are closing this issue.
