### ISSUE TITLE
Add link to the Active IQ MIBS in the SNMP section of the event notification page. 

### ISSUE THREAD

**Issue by binder1234** [NetAppDocs/active-iq-unified-manager#22]
Page: [Notifications page](https://docs.netapp.com/us-en/active-iq-unified-manager/events/reference_notifications_page.html)

Can we add a link to the Active IQ MIBS in the SNMP section?
https://mysupport.netapp.com/site/tools/tool-eula/aiqum-mib

**Comment by netapp-manini** [comment]
Hi @binder1234, thanks for your comments, we will update this issue with a resolution.

**Comment by netapp-shwetav** [comment]
@binder1234 
cc: @netapp-manini 

The information is added to the document. It will be published in the upcoming release.

Regards,
Shweta

**Comment by netapp-shwetav** [comment]
Status-Fixed
Please check the last line of the page-https://docs.netapp.com/us-en/active-iq-unified-manager/events/reference_notifications_page.html#snmp
Closing the issue.
