### ISSUE TITLE
Supported node count

### ISSUE THREAD

**Issue by binder1234** [NetAppDocs/active-iq-unified-manager#23]
Page: [Adding clusters](https://docs.netapp.com/us-en/active-iq-unified-manager/storage-mgmt/task_add_clusters.html)

The add cluster section states

"A single instance of Unified Manager can support a specific number of nodes. If you need to monitor an environment that exceeds the supported node count, you must install an additional instance of Unified Manager to monitor some of the clusters."

We don't list the supported node count in this document. We either need to document this or link to TR-4621. 
https://www.netapp.com/media/13504-tr4621.pdf

**Comment by netapp-manini** [comment]
Thanks @binder1234 for getting back to us. We will look into this suggestion and update this issue when it is resolved.

**Comment by netapp-shwetav** [comment]
@binder1234 
cc: @netapp-manini 
The information is added to the document. It will be published in the upcoming release.

Regards,
Shweta

**Comment by netapp-shwetav** [comment]
Status: Fixed
You can see the updates here-https://docs.netapp.com/us-en/active-iq-unified-manager/storage-mgmt/task_add_clusters.html
Closing this issue.
