### ISSUE TITLE
Add supported types to the add cluster documentation. 

### ISSUE THREAD

**Issue by binder1234** [NetAppDocs/active-iq-unified-manager#29]
Page: [Adding clusters](https://docs.netapp.com/us-en/active-iq-unified-manager/storage-mgmt/task_add_clusters.html)

We currently do not easily specify what types are supported. Unified Manager supports On-premise Ontap clusters, Ontap Select, Cloud Volumes Ontap (CVO). I found some references to Cloud Volumes Ontap in the older release notes but nothing specifically under the add cluster section. There is no mention of Ontap Select in the documents but it is my understanding that it is supported. 

This topic recently came up as a customer was attempting to add an  AWS  FSX Ontap instance to Unified Manager which didn't work. As far as we are aware, FSX is not supported on Unified Manager.

**Comment by netapp-shwetav** [comment]
Thank you for writing us. We are currently investigating the issue and will keep you updated on the progress and the resolution in this thread shortly.

**Comment by netapp-shwetav** [comment]
The information is added to the document. It will be published in the upcoming release.

**Comment by netapp-shwetav** [comment]
The information is published and available here:
https://docs.netapp.com/us-en/active-iq-unified-manager/storage-mgmt/task_add_clusters.html
