### ISSUE TITLE
i think JDK 11 no longer available, perhaps you want to update the page and the example hyperlink to a diff version.

### ISSUE THREAD

**Issue by tomerikko** [NetAppDocs/active-iq-unified-manager#36]
### Page URL

https://docs.netapp.com/us-en/active-iq-unified-manager/install-windows/task_upgrade_openjdk_on_windows_ocum.html

### Page title

Upgrading OpenJDK

### Summary

i think JDK 11 no longer available, perhaps you want to update the page and the example hyperlink to a diff version.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-shwetav** [comment]
Thanks for writing in. We are working on it and will update it with the resolution soon.

**Comment by netapp-shwetav** [comment]
We have updated the link. It will be available with the upcoming release.

**Comment by netapp-shwetav** [comment]
Hi @tomerikko,

We have updated the download link for OpenJDK 11, and the page with the required information.
Thank you for your valuable feedback. 

Regards,
Shweta
