### ISSUE TITLE
Issues with importing encrypted private keys

### ISSUE THREAD

**Issue by binder1234** [NetAppDocs/active-iq-unified-manager#37]
### Page URL

https://docs.netapp.com/us-en/active-iq-unified-manager/config/concept_install_https_certificate_generated_using_external_tools.html

### Page title

Installing a HTTPS certificate generated using external tools

### Summary

Can we link to this KB on how to decrypt or fix incorrect format issues with private keys. 

https://kb.netapp.com/mgmt/AIQUM/AIQUM_fails_to_install_externally_generated_certificate

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-shwetav** [comment]
Thanks for writing in. We are working on it and will update it with the resolution soon.

**Comment by netapp-shwetav** [comment]
Hi @binder1234,

The KB link on how to decrypt or fix incorrect format issues with private keys is added. 
https://docs.netapp.com/us-en/active-iq-unified-manager/config/concept_install_https_certificate_generated_using_external_tools.html#checks-while-uploading-externally-generated-certificates
I am closing the ticket. Please reopen the ticket if you have any concerns.
