### ISSUE TITLE
Quota email notification doesn't work in OnCommand Unified Manager when quota type is QTREE

### ISSUE THREAD

**Issue by hirokazm** [NetAppDocs/active-iq-unified-manager#39]
### Page URL

https://docs.netapp.com/us-en/active-iq-unified-manager/storage-mgmt/task_create_rules_to_generate_email_addresses.html

### Page title

Creating rules to generate email addresses

### Summary

This manual description does not show that Qtree is not supported

https://kb.netapp.com/Legacy/OnCommand_Suite/Quota_email_notification_doesn't_work_in_OnCommand_Unified_Manager_when_quota_type_is_QTREE

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-shwetav** [comment]
Hi @hirokazm,

Thank you for bringing this to our attention. We will look into it and determine how best to address it.

Thans you for helping us improve the quality of our documentation.

Regards,
Shweta

**Comment by netapp-shwetav** [comment]
Hi @hirokazm,
We have updated the document to fix this issue. The revised information is available here:
https://docs.netapp.com/us-en/active-iq-unified-manager/storage-mgmt/task_create_rules_to_generate_email_addresses.html
I am closing the ticket. Please reopen the ticket if you have any concerns.
