### ISSUE TITLE
ACTIVE IQ HTTPS CERTIFICATE AUTOMATION

### ISSUE THREAD

**Issue by alibr1996** [NetAppDocs/active-iq-unified-manager#42]
### Page URL

https://docs.netapp.com/us-en/active-iq-unified-manager/config/concept_manage_security_certificates_ocf.html

### Page title

Managing security certificates

### Summary

Hello , we have 4 Netapp storage arrays and 2 active iq installed on linux machine . Currently I am trying to automate the renew of HTTPS certificates in Active IQ using cli /opt/netapp/essentials/bin/cert.sh . could you explain to me how to use it to renew certificate

Thanks

### Public issues must not contain sensitive information

- [x] This issue contains no sensitive information.

**Comment by netapp-shwetav** [comment]
Hi @alibr1996,

We appreciate you bringing this matter to our notice. We will look into it and promptly provide you with an update.

Regards,
Shweta

**Comment by netapp-shwetav** [comment]
Hi @alibr1996,

We discussed this with the engineers. You can renew the certificate using the Unified Manager maintenance console or web UI. However, there is no available option to renew the certificate using the CLI.
Let me know if you need any more information.
