### ISSUE TITLE
Add antivirus warnings to the Linux installation. 

### ISSUE THREAD

**Issue by binder1234** [NetAppDocs/active-iq-unified-manager#43]
### Page URL

https://docs.netapp.com/us-en/active-iq-unified-manager/install-linux/task_install_unified_manager_linux.html

### Page title

Installing Unified Manager

### Summary

Please add the Antivirus warnings from the Windows installation to the Linux installation and adjust as applicable for Linux. We have run into issues with customers using Qualys on Linux installations. 

If you have an active anti-virus software installed on your Windows system, manually exclude the following paths from anti-virus scan after your installation is complete:

    Unified Manager data directory
    Unified Manager installation directory
    MySQL data directory

The server should be dedicated to running Unified Manager. No other applications should be installed on the server. It is possible that an active anti-virus software is installed on your Windows system because of company regulations. You should disable the anti-virus software before installing Unified Manager to prevent the installation from failing.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-shwetav** [comment]
Hi @binder1234,

Thank you for notifying us.
We will look into it and determine how best to address it.
Thanks again for helping us improve the quality of our documentation.

**Comment by binder1234** [comment]
Any update on this?

**Comment by netapp-shwetav** [comment]
@binder1234:
This issue will be addressed in the upcoming release.

**Comment by netapp-shwetav** [comment]
@binder1234:
We have added the information here:
https://docs.netapp.com/us-en/active-iq-unified-manager/install-linux/reference_red_hat_and_centos_software_and_installation_requirements.html#operating-system-software
I am closing the ticket for now. Please open the ticket again if you have any concerns.

**Comment by netapp-shwetav** [comment]
Hi @binder1234,

@netapp-pcarriga can help you with this.
