### ISSUE TITLE
Two new login will be created is not documented

### ISSUE THREAD

**Issue by ReneMeier** [NetAppDocs/active-iq-unified-manager#46]
### Page URL

https://docs.netapp.com/us-en/active-iq-unified-manager/storage-mgmt/task_add_clusters.html

### Page title

Adding clusters

### Summary

Before adding a cluster in the AIQUM, we create a user called 'user' with application http, ontapi with authentication method "password". The user looks like this:

```
                                                                 Second
User/Group                 Authentication                 Acct   Authentication
Name           Application Method        Role Name        Locked Method
-------------- ----------- ------------- ---------------- ------ --------------
user              http        password      admin            no     none
user              ontapi      password      admin            no     none

2 entries were displayed.
```

After adding the Cluster in the AIQUM successfully (starting with 9.12) the same output looks like this:

```
                                                                 Second
User/Group                 Authentication                 Acct   Authentication
Name           Application Method        Role Name        Locked Method
-------------- ----------- ------------- ---------------- ------ --------------
user              http        cert          admin            no     none
user              ontapi      cert          admin            no     none
user              http        password      admin            no     none
user              ontapi      password      admin            no     none

2 entries were displayed.
```
 
As you can see, the AIQUM create two new entries for this user with the authentication method "cert".  This is not documented.
Please reflect this feature in the documentation in the section **Certificates for Mutual TLS communication**.

Something like this or similar:

![Image 001](https://github.com/NetAppDocs/active-iq-unified-manager/assets/74290973/7fd9acb6-7ae7-4f14-bf21-d430fced2b22)

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ranuk** [comment]
Thank you for reporting the issue. We'll investigate and update the documentation as soon as possible.

**Comment by netapp-ranuk** [comment]
We have updated the documentation https://docs.netapp.com/us-en/active-iq-unified-manager/storage-mgmt/task_add_clusters.html

Thanks!
