### ISSUE TITLE
Incorrect upgrade path.

### ISSUE THREAD

**Issue by binder1234** [NetAppDocs/active-iq-unified-manager#64]
### Page URL

https://docs.netapp.com/us-en/active-iq-unified-manager/install-vapp/task_upgrade_unified_manager_vapp.html

### Page title

Upgrading Unified Manager

### Summary

This page says that you can only upgrade to 9.16 from 9.12 and 9.13.

https://docs.netapp.com/us-en/active-iq-unified-manager/include/upgrade-path.html
-This page indicates that you can upgrade from 9.13 and 9.14 to 9.16

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-maireadn** [comment]
Thanks for the feedback. This page (https://docs.netapp.com/us-en/active-iq-unified-manager/install-vapp/task_upgrade_unified_manager_vapp.html) is updated and now reads: You can upgrade Active IQ Unified Manager to release 9.16 from release 9.13 or 9.14 only.
