### ISSUE TITLE
The release notes link is pointing to 9.14 and not 9.16

### ISSUE THREAD

**Issue by binder1234** [NetAppDocs/active-iq-unified-manager#65]
### Page URL

https://docs.netapp.com/us-en/active-iq-unified-manager/reference_release_notes.html

### Page title

Release notes

### Summary

The release notes link is pointing to 9.14 and not 9.16
https://library.netapp.com/ecm/ecm_download_file/ECMLP2886866

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-maireadn** [comment]
I have updated the link and the release notes are now pointing to 9.16.
