### ISSUE TITLE
Remove Red Hat Enterprise Linux 7 add 9.

### ISSUE THREAD

**Issue by netapp-norbertt** [NetAppDocs/active-iq-unified-manager#68]
### Page URL

https://docs.netapp.com/us-en/active-iq-unified-manager/install-linux/task_manually_configure_epel_repository.html

### Page title

Manually configuring the EPEL repository

### Summary

Please remove "Red Hat Enterprise Linux 7" and add "Red Hat Enterprise Linux 9" on this step as Red Hat Enterprise Linux 7 is not supported.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-maireadn** [comment]
I will look into this as soon as possible. Thanks for bringing it to our attention.

**Comment by netapp-maireadn** [comment]
Thanks for your feedback @netapp-norbertt. This page is now updated.
