### ISSUE TITLE
Support for RHEL7 has been removed and support for RHEL9 has been added. 

### ISSUE THREAD

**Issue by binder1234** [NetAppDocs/active-iq-unified-manager#69]
### Page URL

https://docs.netapp.com/us-en/active-iq-unified-manager/install-linux/task_manually_configure_epel_repository.html

### Page title

Manually configuring the EPEL repository

### Summary

We need to remove the EPEL link for RHEL7 in the UM 9.16 documentation and add a link for RHEL9. We have removed support for RHEL7 and now support RHEL9.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-maireadn** [comment]
Thanks for your feedback. RHEL 9 was updated a few days ago on this page: https://docs.netapp.com/us-en/active-iq-unified-manager/install-linux/task_manually_configure_epel_repository.html
