### ISSUE TITLE
Upload Rules Button Not Visible

### ISSUE THREAD

**Issue by jogeorg2** [NetAppDocs/active-iq-unified-manager#9]
Page: [Uploading a new Active IQ rules file](https://docs.netapp.com/us-en/active-iq-unified-manager/events/task_upload_new_active_iq_rules_file.html) - I have version 9.10, 9.10P1, and 9.11RC1 AIQUMs and none of them have the Upload Rules button mentioned on the Storage Management > Event Setup page.

**Comment by netapp-manini** [comment]
Hi John, thanks for raising this issue. Please check this screen grab where the button is seen. Please check if this button is visible on your system. I am keeping this issue open to check with the team on whether this button is visible in certain conditions and is not available in some other. 

![image](https://user-images.githubusercontent.com/59729581/172646572-b4746f4d-f1fd-4fb6-9a89-8224d8ba0d99.png)

**Comment by jogeorg2** [comment]
Hi Manini,
 
This screen grab is from my 9.11RC1 AIQUM –
![image](https://user-images.githubusercontent.com/67762449/172669069-e50b2a35-641d-4db8-9f09-39091a67dfab.png)
 

 
This one is from a 9.10 AIQUM –
![image](https://user-images.githubusercontent.com/67762449/172669113-31d76221-1645-44a6-9d40-9bd8affd9839.png) 
And this one is from 9.10P1 –
![image](https://user-images.githubusercontent.com/67762449/172669161-301a7624-bb24-4cb6-975b-e6129f39fe8e.png)

 
As you can see, none of them have the Upload Rules button. These screengrabs were done with Edge as the browser, but I have seen the same thing with Chrome.

**Comment by netapp-manini** [comment]
I will go to the engg team for this, however, the topic mentions this:

Active IQ portal event reporting must be enabled. This feature is enabled by default. For information, see [Enabling Active IQ portal events](https://docs.netapp.com/us-en/active-iq-unified-manager/config/concept_active_iq_platform_events.html).

Can you please ensure once whether this setting is enabled on your side?

**Comment by jogeorg2** [comment]
Hi Manini,

If you look at the screenshots, you will see that event reporting is enabled.

Thanks,
[http://www.cisco.com/c/dam/assets/email-signature-tool/logo_01.png?ct=1449765778181]
John George
ENGINEER.TECHNICAL MARKETING

***@***.******@***.***>
Phone: +1 984 216 4505

Cisco.com<http://www.cisco.com>

[http://www.cisco.com/assets/swa/img/thinkbeforeyouprint.gif] Think before you print.
This email may contain confidential and privileged material for the sole use of the intended recipient. Any review, use, distribution or disclosure by others is strictly prohibited. If you are not the intended recipient (or authorized to receive for the recipient), please contact the sender by reply email and delete all copies of this message.
Please click here<http://www.cisco.com/web/about/doing_business/legal/cri/index.html> for Company Registration Information.


From: Manini Mandal ***@***.***>
Reply-To: NetAppDocs/active-iq-unified-manager ***@***.***>
Date: Thursday, June 9, 2022 at 1:01 AM
To: NetAppDocs/active-iq-unified-manager ***@***.***>
Cc: John George ***@***.***>, Author ***@***.***>
Subject: Re: [NetAppDocs/active-iq-unified-manager] Upload Rules Button Not Visible (Issue #9)


I will go to the engg team for this, however, the topic mentions this:

Active IQ portal event reporting must be enabled. This feature is enabled by default. For information, see Enabling Active IQ portal events<https://docs.netapp.com/us-en/active-iq-unified-manager/config/concept_active_iq_platform_events.html>.

Can you please ensure once whether this setting is enabled on your side?

**Comment by netapp-manini** [comment]
Hi John, this issue is identified in a recent BURT and the workaround is available at this link:

https://mysupport.netapp.com/site/bugs-online/product/AIQUM/BURT/1471536 

This issue has been resolved in Active IQ Unified Manager 9.11 RC1. I am closing this doc query. For further queries, you can send emails to the engineering contacts on this BURT.

**Comment by netapp-manini** [comment]
Hi, added BURT 1489738 for this issue. When fixed, will update this thread.

**Comment by netapp-manini** [comment]
Hi John, 

Because we did not hear back from you, writing in to let you know that the KB article mentioned in the Public Report for the BURT has the resolution that you are seeking for OVA. I will add the link to this KB on this section. When the guides are released, I will close this issue. Do let me know of any further queries.

Thanks,
Manini

**Comment by jogeorg2** [comment]
Thanks, Manini, sounds good.

Thanks,
[http://www.cisco.com/c/dam/assets/email-signature-tool/logo_01.png?ct=1449765778181]
John George
ENGINEER.TECHNICAL MARKETING

***@***.******@***.***>
Phone: +1 984 216 4505

Cisco.com<http://www.cisco.com>

[http://www.cisco.com/assets/swa/img/thinkbeforeyouprint.gif] Think before you print.
This email may contain confidential and privileged material for the sole use of the intended recipient. Any review, use, distribution or disclosure by others is strictly prohibited. If you are not the intended recipient (or authorized to receive for the recipient), please contact the sender by reply email and delete all copies of this message.
Please click here<http://www.cisco.com/web/about/doing_business/legal/cri/index.html> for Company Registration Information.


From: Manini Mandal ***@***.***>
Reply-To: NetAppDocs/active-iq-unified-manager ***@***.***>
Date: Thursday, July 14, 2022 at 8:24 AM
To: NetAppDocs/active-iq-unified-manager ***@***.***>
Cc: John George ***@***.***>, Author ***@***.***>
Subject: Re: [NetAppDocs/active-iq-unified-manager] Upload Rules Button Not Visible (Issue #9)


Hi John,

Because we did not hear back from you, writing in to let you know that the KB article mentioned in the Public Report for the BURT has the resolution that you are seeking for OVA. I will add the link to this KB on this section. When the guides are released, I will close this issue. Do let me know of any further queries.

Thanks,
Manini

**Comment by netapp-manini** [comment]
The link has been added to https://docs.netapp.com/us-en/active-iq-unified-manager/events/task_upload_new_active_iq_rules_file.html 

Closing the issue
